### ISSUE TITLE
GT++ Casings textures

### ISSUE THREAD

**Issue by Slurpassassin** [Ethryan/GTNH-Faithful-Textures#11]
The GT++ multiblock casings are in the code but appear to be the same as default. Would it be possible to make these casings in the same style as the Gregtech multiblock casings?

**Comment by Ethryan** [comment]
I will look into it.

**Comment by Nxer** [comment]
@Ethryan 
![2023-10-22_04 47 46](https://github.com/Ethryan/GTNH-Faithful-Textures/assets/43300390/113a6b3d-3e71-4278-8fa1-b97c19e77b07)

**Comment by Ethryan** [comment]
> @Ethryan
> ![2023-10-22_04 47 46](https://user-images.githubusercontent.com/43300390/277133163-113a6b3d-3e71-4278-8fa1-b97c19e77b07.png)

I was waiting to see what direction the 16x16 textures were going, there have been talk about replacing them.
