### ISSUE TITLE
16x top layer in texture pack

### ISSUE THREAD

**Issue by 905Sunny** [Ethryan/GTNH-Faithful-Textures#13]
![2022-02-03_23 47 08](https://user-images.githubusercontent.com/44795811/152378554-6a8497e6-eb98-4592-ae9b-891160db7b0a.png)

Is your resourcepack supposed to change this? (the 16x part in the EBF block)

**Comment by Ethryan** [comment]
I havn't gotten to that one yet.

This pack is a work in progress. I add new textures when i have time and motivation.
