### ISSUE TITLE
Glow texture on BBF gone wrong

### ISSUE THREAD

**Issue by 905Sunny** [Ethryan/GTNH-Faithful-Textures#14]
![2022-02-15_00 12 35](https://user-images.githubusercontent.com/44795811/153902025-af4a9c76-bfea-4c9c-a04e-b033546607b2.png)

I didn't see this coming...

**Comment by Ethryan** [comment]
Hmm, will check this out tomorrow

**Comment by Pyromanc3r** [comment]
It should be notified that this bug appears during the BBF work process. In idle mode everything is fine.

**Comment by Ethryan** [comment]
This is an transperancy in the overlay error, It's fixed now.
