### ISSUE TITLE
Cosmic neutronium texture error

### ISSUE THREAD

**Issue by Szajkop** [Ethryan/GTNH-Faithful-Textures#19]
![image](https://user-images.githubusercontent.com/7230430/188168288-6141c953-5218-4100-86a7-24d0daacff6f.png)

This happens when im using the GTNH-Faithful-Textures.0.9.1.zip 
I tried deleting assets/avaritia folder and it fixed the problem but this way the other avaritia textures also changed back to default

**Comment by Ethryan** [comment]
Will look into it
