### ISSUE TITLE
Issue about the texutre showed on server

### ISSUE THREAD

**Issue by SoulAttacker** [Ethryan/GTNH-Faithful-Textures#30]
Hi! Nice day! I love your texutre pack!! But, I occurred some problems when I use this texture pack in my private server. I showed some cases in the following video. Thank you for your reply~ 

## Problem Description
When I use this texutre, it works perfectly in my single save, but, when I join my private server, the cursor just like blink with a white background, the texutre works on the machines and items, only works weird when I join the server.

## Which version of the texutre pack
[0.9.8](https://github.com/Ethryan/GTNH-Faithful-Textures/releases/tag/0.9.8)

## GTNH version
2.6.1

## Other texture packs?
No, just this texture and the default texture.

## Angelica Version
1.0.0-alpha52

## Video

https://github.com/Ethryan/GTNH-Faithful-Textures/assets/49908231/8c5ce3c8-f729-4e2b-89a9-b5b38c7fc615

**Comment by Ethryan** [comment]
I can't see the video, It just says its unavailable when I try and watch it.

**Comment by SoulAttacker** [comment]
Well, actually, it doesn't works after I disabled GL State Cache. One thing, Angelica maybe used only in the client. But that's Ok, the cursor doesn't matter me. Thank you again for your nice work! Have a nice day :)

**Comment by SoulAttacker** [comment]
Hello and nice day! After I upgrade the latest angelica mod (angelica-1.0.0 beta1) the problem has been solved, and thank you again for your nice work! I will close this issue :)
