### ISSUE TITLE
Wrong ingot cast position?

### ISSUE THREAD

**Issue by Edgars-Cirulis** [Ethryan/GTNH-Faithful-Textures#37]
With texturepack:
![image](https://github.com/user-attachments/assets/74c2d3c7-cf50-4e1e-8f61-a0f84ff4a134)

Stock:
![image](https://github.com/user-attachments/assets/68fae490-fdb6-4b85-bdf5-a3de42a8bc16)

**Comment by Ethryan** [comment]
Its the same with the original cast, just the hole is smaller so the ingot covers it

**Comment by Edgars-Cirulis** [comment]
> Its the same with the original cast, just the hole is smaller so the ingot covers it

it seems copper and bronze are in wrong position

![image](https://github.com/user-attachments/assets/54628278-1245-4b82-954c-f54d50ce56c1)


and others are fine like this

![image](https://github.com/user-attachments/assets/a8877e0e-4d8a-447a-9c79-a8bb9c6dbf28)

**Comment by Ethryan** [comment]
It depends on what mod the item is from, vanilla and certain mods work fine.
GT itms are flipped. Its a trade off, but I got no clue how to fix it. And I won’t touch GT rendering code, that stuff is seriously hard to understand.

**Comment by Tome-Wyrm** [comment]
Don't suppose you could flip the mold and the ingots not from gregtech?

Or make the hole smaller?

**Comment by Ethryan** [comment]
Don’t think I will do that, since I’ve gotten used to it already.
