### ISSUE TITLE
16x16 Textures for some Natura berries and blocks

### ISSUE THREAD

**Issue by Mihnea229** [Ethryan/GTNH-Faithful-Textures#39]
Some Natura berries and plants have the "vanilla" 16x16 textures: 
![2024-09-01_18 45 24](https://github.com/user-attachments/assets/7a8df9f7-915e-433a-a1d4-5281cd1f5eca)
<img width="529" alt="2024-09-01_18 47 06" src="https://github.com/user-attachments/assets/8b3db992-2bdd-483c-8465-589992013cee">

**Comment by Mihnea229** [comment]
In a normal Natura version the plants already have 32x32 textures, but in GTNH, to make all the textures consistent, they have 16x textures.

**Comment by Ethryan** [comment]
Ok, will fix this
